apiVersion: argoproj.io
kind: Workflow
metadata:
  generateName: geospatialdata
  project_name : "DATACUBE"
  use_case: "GLOBAL"
  
chirpsArguments:
    pathforTGZ: "/home/ubuntu/datalake/src/chirps/tgz/"
    pathforNCDF: "/home/ubuntu/datalake/src/chirps/nc/"
    awsChirpsLandingPath: "s3://climate-action-datalake/zone=landing/source=CHIRPS/variable=precipitation/"
    awsChirpsRawPath: "s3://climate-action-datalake/zone=raw/source=chirps/variable=precipitation.zarr/"
    awsChirpsTemporalPath: "s3://climate-action-datalake/zone=temporal/source=chirps/variable=precipitation/"
